spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mariadb://localhost:3308/mydb
    username: myadmin
    password: rkskekfk1
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.godcoder: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  jpa:
    properties:
      hibernate:
        format_sql: true


mybatis:
  type-aliases-package: com.godcoder.myhome.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml