spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mariadb://localhost:3308/mydb
    username: myadmin
    password: rkskekfk1
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug
    com.pisien: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace   # 쿼리 파라미터 로그 남기기

  jpa:
    hibernate:                          #    open-in-view: false   # OSIV종료 (Off Session In View) : 커넥션 풀 부족현상 해결
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000  # 성능최적화를 위한 페이지 옵션
        use_sql_comment: true

  data:
    web:
      pageable:
        default-page-size: 5            # 페이지 사이즈
        max-page-size: 2000             # 최대 사이즈
#        one-indexed-parameters: true   #  index 설정 0 or 1


mybatis:
  type-aliases-package: com.pisien.myhome.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml